### ISSUE TITLE
stable-diffusion-webui-forge是否需要安装sd-webui-model-patcher

### ISSUE THREAD

**Issue by yeyugong** [huchenlei/sd-forge-ic-light#31]
下列报错怎么处理：*** Error running before_process: E:\AGI\stable-diffusion-forge\webui\extensions\sd-forge-ic-light\scripts\ic_light_script.py
    Traceback (most recent call last):
      File "E:\AGI\stable-diffusion-forge\webui\modules\scripts.py", line 790, in before_process
        script.before_process(p, *script_args)
      File "E:\AGI\stable-diffusion-forge\webui\extensions\sd-forge-ic-light\scripts\ic_light_script.py", line 257, in before_process
        args = ICLightArgs.fetch_from(p)
      File "E:\AGI\stable-diffusion-forge\webui\extensions\sd-forge-ic-light\libiclight\args.py", line 210, in fetch_from
        return ICLightArgs(**args[0])
      File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
      File "pydantic\main.py", line 1074, in pydantic.main.validate_model
      File "pydantic\fields.py", line 864, in pydantic.fields.ModelField.validate
      File "pydantic\fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
      File "pydantic\class_validators.py", line 304, in pydantic.class_validators._generic_validator_cls.lambda4
      File "E:\AGI\stable-diffusion-forge\webui\extensions\sd-forge-ic-light\libiclight\args.py", line 168, in parse_model_type
        return ModelType.get(value)
      File "E:\AGI\stable-diffusion-forge\webui\extensions\sd-forge-ic-light\libiclight\model_loader.py", line 47, in get
        raise SystemError
    SystemError

**Comment by huchenlei** [comment]
Follow instructions in README. https://github.com/huchenlei/sd-forge-ic-light#2024-06-06-major-update-release-note-pr-httpsgithubcomhuchenleisd-forge-ic-lightpull24

You likely need to rename your unet folder to ic-light on the update.
