### ISSUE TITLE
Unable to generate results even after matching sample settings

### ISSUE THREAD

**Issue by Nesuhst** [huchenlei/sd-forge-ic-light#9]
<img width="764" alt="Screenshot 2024-05-16 230339" src="https://github.com/huchenlei/sd-forge-ic-light/assets/110304717/c59f1436-b692-4a22-bcef-4484d14f093d">

The ouput picture never seems to relate to the input image in any of the options. 

I'm forge on the latest version. 
I'd followed the instructions to create a "Unet" folder in the forge > webui > models > folder where I'd put the ic-light safetensors, as there wasn't one yet. 

running on a 980ti 6gb

for some reason, at the start of the generation, the input ic-light image is shown but then fades completely to an unrelated image (in txt2img at least, but I think it's similar in img2img)

<img width="392" alt="Screenshot 2024-05-16 231542" src="https://github.com/huchenlei/sd-forge-ic-light/assets/110304717/cc91dbd3-d0e1-43b4-b6e5-4965164f273e">

<img width="389" alt="Screenshot 2024-05-16 231902" src="https://github.com/huchenlei/sd-forge-ic-light/assets/110304717/5ef17943-457c-481b-932f-884d527fe38b">

**Comment by Dreamz-Dziner** [comment]
For me also nothing seems to be working even after doing exactly the same things mentioned in the repo page. The resulting image does not  match with the foreground uploaded. Not sure what went wrong.

**Comment by huchenlei** [comment]
Can you attach full console log? Thanks

**Comment by Dreamz-Dziner** [comment]
> Can you attach full console log? Thanks

There is no error message as such in the console which is the confusing part. ![Console](https://github.com/huchenlei/sd-forge-ic-light/assets/69266893/7ecee1f6-dd8e-4ac7-8793-3441a51e3c83)

**Comment by Dreamz-Dziner** [comment]
Here is what I get in the UI section 
![1](https://github.com/huchenlei/sd-forge-ic-light/assets/69266893/0c6fc4c1-acb8-481d-80a4-797f79ecc1b0)

**Comment by Ignacio50** [comment]
Same here, this is what I got on the console log
`
*** Error running process_before_every_sampling: E:\stable-diffusion-webui\extensions\sd-forge-ic-light\scripts\forge_ic_light.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
        response.raise_for_status()
      File "E:\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/briaai/RMBG-1.4/resolve/main/model.safetensors

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-forge-ic-light\scripts\forge_ic_light.py", line 403, in process_before_every_sampling
        rmbg = BriaRMBG.from_pretrained("briaai/RMBG-1.4").to(device=device)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hub_mixin.py", line 277, in from_pretrained
        instance = cls._from_pretrained(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hub_mixin.py", line 492, in _from_pretrained
        model_file = hf_hub_download(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1403, in hf_hub_download
        raise head_call_error
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1261, in hf_hub_download
        metadata = get_hf_file_metadata(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1667, in get_hf_file_metadata
        r = _request_wrapper(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
        response = _request_wrapper(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 409, in _request_wrapper
        hf_raise_for_status(response)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 321, in hf_raise_for_status
        raise GatedRepoError(message, response) from e
    huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. 

    Cannot access gated repo for url https://huggingface.co/briaai/RMBG-1.4/reso
lve/main/model.safetensors.
    Access to model briaai/RMBG-1.4 is restricted. You must be authenticated to
access it.

---
`
Now I did like @CasualDev242 mentions, create a hugging face account, download the model.safetensors, put it in the same unet folder, and I still can't get it to work.

**Comment by quangchi** [comment]
Has anyone been able to fix this problem yet?
I see a few people on YouTube have installed it (https://www.youtube.com/watch?v=WSBkgXnQBkU)
. But I do not

**Comment by hiend0001** [comment]
Hi,quangchi
What GPU are you using?

**Comment by Haoming02** [comment]
Hello, you may try out my [fork](https://github.com/Haoming02/sd-forge-ic-light) in the meantime, which uses the same `rembg` package as [stable-diffusion-webui-rembg](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg) that automatically downloads the models, among some other UI improvements.

**Comment by huchenlei** [comment]
> Hello, you may try out my [fork](https://github.com/Haoming02/sd-forge-ic-light) in the meantime, which uses the same `rembg` package as [stable-diffusion-webui-rembg](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg) that automatically downloads the models, among some other UI improvements.

Thanks! Would you like your change merged here as well? I can add you as collaborator of this repo.

**Comment by huchenlei** [comment]
Amazing, you even implemented the detail restore that I planned to do a while ago. 👍

**Comment by Haoming02** [comment]
Well, I did make a few fundmental changes *(**eg.** the model loading parts)*. But if you're fine with them, then merging is fine ig
